package janelas;

import componentes.FormattedTextCNPJ;
import componentes.FormattedTextCPF;

/**
 *
 * @author Andre Luis
 */
public class FrameCadastroFornecedor extends javax.swing.JInternalFrame {

    /** Creates new form NewFrameCadastroFornecedor */
    public FrameCadastroFornecedor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDadosEmpresa = new javax.swing.JLabel();
        lblCodigoEmpresa = new javax.swing.JLabel();
        ftxtCodigoEmpresa = new componentes.FormattedTextNumero();
        lblClassificacao = new javax.swing.JLabel();
        rdbJurifica = new javax.swing.JRadioButton();
        rdbFisica = new javax.swing.JRadioButton();
        lblRegistro = new javax.swing.JLabel();
        ftxtRegistro = new javax.swing.JFormattedTextField();
        lblInscricaoEstadual = new javax.swing.JLabel();
        txtInscricaoEstadual = new javax.swing.JTextField();
        lblRazaoSocial = new javax.swing.JLabel();
        txtRazaoSocial = new javax.swing.JTextField();
        lblNomeFantasia = new javax.swing.JLabel();
        txtNomeFantasia = new javax.swing.JTextField();
        lblEnderecoEmpresa = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCEP = new javax.swing.JLabel();
        ftxtCep = new componentes.FormattedTextCEP();
        lblEstado = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox();
        lblEstado1 = new javax.swing.JLabel();
        cmbCidade = new javax.swing.JComboBox();
        lblDadosContato = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        formattedTextTelefone1 = new componentes.FormattedTextTelefone();
        lblTelefone3 = new javax.swing.JLabel();
        formattedTextTelefone3 = new componentes.FormattedTextTelefone();
        lblTelefone1 = new javax.swing.JLabel();
        formattedTextTelefone2 = new componentes.FormattedTextTelefone();
        lblTelefone2 = new javax.swing.JLabel();
        formattedTextEmail1 = new componentes.FormattedTextEmail();
        lblHomepage = new javax.swing.JLabel();
        txtHomepage1 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastro de Fornecedor - Gestor Contábil");

        lblDadosEmpresa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDadosEmpresa.setText("Dados da Empresa");

        lblCodigoEmpresa.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblCodigoEmpresa.setText("Código da Empresa:");

        lblClassificacao.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblClassificacao.setText("Classificação");

        rdbJurifica.setText("Jurídica");
        rdbJurifica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbJurificaItemStateChanged(evt);
            }
        });
        rdbJurifica.setSelected(true);

        rdbFisica.setText("Física");
        rdbFisica.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbFisicaItemStateChanged(evt);
            }
        });

        lblRegistro.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblRegistro.setText("CNPJ ou CPF");

        ftxtRegistro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtRegistrovalidarRegistro(evt);
            }
        });

        lblInscricaoEstadual.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblInscricaoEstadual.setText("Inscrição Estadual");

        lblRazaoSocial.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblRazaoSocial.setText("Razão Social");

        lblNomeFantasia.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblNomeFantasia.setText("Nome Fantasia");

        lblEnderecoEmpresa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEnderecoEmpresa.setText("Endereço da Empresa");

        lblEndereco.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblEndereco.setText("Endereço");

        lblBairro.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblBairro.setText("Bairro");

        lblCEP.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblCEP.setText("CEP");

        lblEstado.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblEstado.setText("Estado");

        lblEstado1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblEstado1.setText("Cidade");

        lblDadosContato.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDadosContato.setText("Dados de Contato da Empresa");

        lblTelefone.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblTelefone.setText("Telefone");

        lblTelefone3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblTelefone3.setText("Celular");

        lblTelefone1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblTelefone1.setText("Fax");

        lblTelefone2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblTelefone2.setText("E-mail");

        lblHomepage.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblHomepage.setText("Homepage:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblDadosEmpresa)
                        .addGap(153, 153, 153)
                        .addComponent(lblEnderecoEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCodigoEmpresa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ftxtCodigoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtNomeFantasia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                            .addComponent(txtRazaoSocial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(rdbJurifica)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rdbFisica))
                                            .addComponent(lblClassificacao, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblRegistro)
                                                    .addComponent(ftxtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtInscricaoEstadual, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                                    .addComponent(lblInscricaoEstadual))))
                                        .addGap(41, 41, 41))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRazaoSocial)
                                        .addGap(239, 239, 239)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNomeFantasia)
                                    .addGap(226, 226, 226)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblEstado1)
                                .addComponent(txtBairro)
                                .addComponent(lblEndereco)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                .addComponent(lblBairro)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCEP)
                                        .addComponent(ftxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblEstado)))
                                .addComponent(cmbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblDadosContato)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(formattedTextTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefone)
                            .addComponent(lblTelefone3)
                            .addComponent(formattedTextTelefone3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefone1)
                            .addComponent(formattedTextTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefone2)
                            .addComponent(formattedTextEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(lblHomepage)
                            .addComponent(txtHomepage1))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoEmpresa)
                    .addComponent(ftxtCodigoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDadosEmpresa)
                    .addComponent(lblEnderecoEmpresa)
                    .addComponent(lblDadosContato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEndereco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbJurifica)
                            .addComponent(rdbFisica)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRegistro)
                            .addComponent(lblInscricaoEstadual)
                            .addComponent(lblBairro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftxtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblRazaoSocial)
                                    .addComponent(lblCEP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ftxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNomeFantasia)
                                    .addComponent(lblEstado1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formattedTextTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTelefone3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formattedTextTelefone3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTelefone1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formattedTextTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTelefone2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formattedTextEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHomepage)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHomepage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbJurificaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbJurificaItemStateChanged
        if(rdbJurifica.isSelected()){
            ftxtRegistro.setValue(null);
            FormattedTextCNPJ f = new FormattedTextCNPJ();
            ftxtRegistro.setFormatterFactory(f.getFormatterFactory());
        }
}//GEN-LAST:event_rdbJurificaItemStateChanged

    private void rdbFisicaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbFisicaItemStateChanged
        if(rdbFisica.isSelected()){
            ftxtRegistro.setValue(null);
            FormattedTextCPF f = new FormattedTextCPF();
            ftxtRegistro.setFormatterFactory(f.getFormatterFactory());
        }
}//GEN-LAST:event_rdbFisicaItemStateChanged

    private void ftxtRegistrovalidarRegistro(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtRegistrovalidarRegistro
        if(rdbJurifica.isSelected()){
            FormattedTextCNPJ f = new FormattedTextCNPJ();
            f.setText(ftxtRegistro.getText());
            if(!f.validarCNPJ()){
                ftxtRegistro.setValue(null);
            }
            return;
        }
        if(rdbFisica.isSelected()){
            FormattedTextCPF f = new FormattedTextCPF();
            f.setText(ftxtRegistro.getText());
            if(!f.validarCPF()){
                ftxtRegistro.setValue(null);
            }
            return;
        }
}//GEN-LAST:event_ftxtRegistrovalidarRegistro


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCidade;
    private javax.swing.JComboBox cmbEstado;
    private componentes.FormattedTextEmail formattedTextEmail1;
    private componentes.FormattedTextTelefone formattedTextTelefone1;
    private componentes.FormattedTextTelefone formattedTextTelefone2;
    private componentes.FormattedTextTelefone formattedTextTelefone3;
    private componentes.FormattedTextCEP ftxtCep;
    private componentes.FormattedTextNumero ftxtCodigoEmpresa;
    private javax.swing.JFormattedTextField ftxtRegistro;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblClassificacao;
    private javax.swing.JLabel lblCodigoEmpresa;
    private javax.swing.JLabel lblDadosContato;
    private javax.swing.JLabel lblDadosEmpresa;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEnderecoEmpresa;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblHomepage;
    private javax.swing.JLabel lblInscricaoEstadual;
    private javax.swing.JLabel lblNomeFantasia;
    private javax.swing.JLabel lblRazaoSocial;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTelefone1;
    private javax.swing.JLabel lblTelefone2;
    private javax.swing.JLabel lblTelefone3;
    private javax.swing.JRadioButton rdbFisica;
    private javax.swing.JRadioButton rdbJurifica;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtHomepage1;
    private javax.swing.JTextField txtInscricaoEstadual;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtRazaoSocial;
    // End of variables declaration//GEN-END:variables

}
