package janelas;

/**
 *
 * @author Táizel Girão
 */
public class FrameSobre extends ModalInternalFrame {

    private static FrameSobre frame;

    /**Construtor padrão do JDesktopPane*/
    public FrameSobre() {
        initComponents();
        
    }

    /**Retorna a instância atual de FrameSobre, se não existir nenhuma ele cria uma e a retorna.
     * @return A instância atual de FrameSobre, se não existir nenhuma ele cria uma e a retorna.
     */
    public static FrameSobre getInstance() {
        if (frame == null) {
            frame = new FrameSobre();
        }
        return frame;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lnlNome = new javax.swing.JLabel();
        lblVersao = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        setClosable(true);
        setTitle("Sobre");

        lnlNome.setText("Gestor Contábil");

        lblVersao.setText("Versão 0.1");

        lblEmpresa.setText("Grupo Analisi - Soluções em TI");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnlNome)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVersao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                        .addComponent(lblEmpresa)
                        .addGap(49, 49, 49))))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(btnOK)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lnlNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVersao)
                    .addComponent(lblEmpresa))
                .addGap(43, 43, 43)
                .addComponent(btnOK)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblVersao;
    private javax.swing.JLabel lnlNome;
    // End of variables declaration//GEN-END:variables
}
