/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrameCadastroProduto.java
 *
 * Created on 10/03/2009, 13:31:32
 */

package janelas;

/**
 *
 * @author Andre Luis
 */
public class FrameCadastroProduto extends ModalInternalFrame {

    /** Creates new form FrameCadastroProduto */
    public FrameCadastroProduto() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatusProduto = new javax.swing.JLabel();
        rdbAtivo = new javax.swing.JRadioButton();
        rdbInativo = new javax.swing.JRadioButton();
        lblTipoProduto = new javax.swing.JLabel();
        rdbMateriaPrima = new javax.swing.JRadioButton();
        rdbDiversos = new javax.swing.JRadioButton();
        rdbProducaoPropria = new javax.swing.JRadioButton();
        lblCodigoProduto = new javax.swing.JLabel();
        ftxtCodigoProduto = new componentes.FormattedTextNumero();
        lblCodigoBarra = new javax.swing.JLabel();
        lblCodigoFabricante = new javax.swing.JLabel();
        txtCodigoFabricante = new javax.swing.JTextField();
        lblNumeroSerie = new javax.swing.JLabel();
        txtNumeroSerie = new javax.swing.JTextField();
        lblLocalizacaoProduto = new javax.swing.JLabel();
        txtLocalizacaoProduto = new javax.swing.JTextField();
        lblUltimaCompra = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtPesoM = new javax.swing.JTextField();
        lblUltimaVenda = new javax.swing.JLabel();
        txtUltimaVenda = new javax.swing.JTextField();
        lblPesoM = new javax.swing.JLabel();
        txtUnidade = new javax.swing.JTextField();
        txtPesoBruto = new javax.swing.JTextField();
        lblPesoLiquido = new javax.swing.JLabel();
        txtPesoLiquido = new javax.swing.JTextField();
        lblPesoBruto = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        txtUltimaCompra = new javax.swing.JTextField();
        lblUnidade = new javax.swing.JLabel();
        txtCodigoBarra = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastro de Produto - Gestor Contábil");

        lblStatusProduto.setFont(new java.awt.Font("Dialog", 1, 11));
        lblStatusProduto.setText("Status do Produto");

        rdbAtivo.setText("Ativo");

        rdbInativo.setText("Inativo");

        lblTipoProduto.setFont(new java.awt.Font("Dialog", 1, 11));
        lblTipoProduto.setText("Tipo de produto");

        rdbMateriaPrima.setText("Matéria Prima");

        rdbDiversos.setText("Diversos");

        rdbProducaoPropria.setText("Produção Própria");

        lblCodigoProduto.setFont(new java.awt.Font("Dialog", 1, 11));
        lblCodigoProduto.setText("Código do Produto");

        lblCodigoBarra.setFont(new java.awt.Font("Dialog", 1, 11));
        lblCodigoBarra.setText("Código de Barra (EAN13)");

        lblCodigoFabricante.setFont(new java.awt.Font("Dialog", 1, 11));
        lblCodigoFabricante.setText("Código do Fabricante");

        lblNumeroSerie.setFont(new java.awt.Font("Dialog", 1, 11));
        lblNumeroSerie.setText("Número de Série");

        lblLocalizacaoProduto.setFont(new java.awt.Font("Dialog", 1, 11));
        lblLocalizacaoProduto.setText("Localização do Produto");

        lblUltimaCompra.setFont(new java.awt.Font("Dialog", 1, 11));
        lblUltimaCompra.setText("Última Compra");

        lblUltimaVenda.setFont(new java.awt.Font("Dialog", 1, 11));
        lblUltimaVenda.setText("Última Venda");

        lblPesoM.setFont(new java.awt.Font("Dialog", 1, 11));
        lblPesoM.setText("Peso m²");

        lblPesoLiquido.setFont(new java.awt.Font("Dialog", 1, 11));
        lblPesoLiquido.setText("Peso Líquido");

        lblPesoBruto.setFont(new java.awt.Font("Dialog", 1, 11));
        lblPesoBruto.setText("Peso Bruto");

        lblDescricao.setFont(new java.awt.Font("Dialog", 1, 11));
        lblDescricao.setText("Descrição");

        lblUnidade.setFont(new java.awt.Font("Dialog", 1, 11));
        lblUnidade.setText("Unidade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatusProduto)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbAtivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdbInativo)))
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoProduto)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescricao)
                                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(161, 161, 161)
                                                .addComponent(txtUltimaVenda))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(161, 161, 161)
                                                .addComponent(txtPesoLiquido))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtPesoM)
                                                    .addComponent(lblPesoM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtUnidade)
                                                    .addComponent(lblUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(24, 24, 24)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(txtUltimaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(12, 12, 12))
                                                        .addComponent(lblUltimaCompra))
                                                    .addComponent(txtPesoBruto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblPesoBruto, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblUltimaVenda)
                                                    .addComponent(lblPesoLiquido))))
                                        .addGap(1, 1, 1)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rdbMateriaPrima)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rdbDiversos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rdbProducaoPropria)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtLocalizacaoProduto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCodigoFabricante, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCodigoFabricante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCodigoProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ftxtCodigoProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigoBarra)
                                .addComponent(lblCodigoBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNumeroSerie)
                                .addComponent(txtNumeroSerie))))
                    .addComponent(lblLocalizacaoProduto))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusProduto)
                    .addComponent(lblTipoProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbAtivo)
                    .addComponent(rdbInativo)
                    .addComponent(rdbMateriaPrima)
                    .addComponent(rdbDiversos)
                    .addComponent(rdbProducaoPropria))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigoProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ftxtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCodigoFabricante)
                                    .addComponent(lblNumeroSerie)))
                            .addComponent(lblCodigoBarra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLocalizacaoProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocalizacaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDescricao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblUnidade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblPesoM)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPesoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPesoBruto)
                                .addComponent(lblPesoLiquido))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPesoBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblUltimaCompra)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtUltimaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtPesoLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblUltimaVenda)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtUltimaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.FormattedTextNumero ftxtCodigoProduto;
    private javax.swing.JLabel lblCodigoBarra;
    private javax.swing.JLabel lblCodigoFabricante;
    private javax.swing.JLabel lblCodigoProduto;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblLocalizacaoProduto;
    private javax.swing.JLabel lblNumeroSerie;
    private javax.swing.JLabel lblPesoBruto;
    private javax.swing.JLabel lblPesoLiquido;
    private javax.swing.JLabel lblPesoM;
    private javax.swing.JLabel lblStatusProduto;
    private javax.swing.JLabel lblTipoProduto;
    private javax.swing.JLabel lblUltimaCompra;
    private javax.swing.JLabel lblUltimaVenda;
    private javax.swing.JLabel lblUnidade;
    private javax.swing.JRadioButton rdbAtivo;
    private javax.swing.JRadioButton rdbDiversos;
    private javax.swing.JRadioButton rdbInativo;
    private javax.swing.JRadioButton rdbMateriaPrima;
    private javax.swing.JRadioButton rdbProducaoPropria;
    private javax.swing.JTextField txtCodigoBarra;
    private javax.swing.JTextField txtCodigoFabricante;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtLocalizacaoProduto;
    private javax.swing.JTextField txtNumeroSerie;
    private javax.swing.JTextField txtPesoBruto;
    private javax.swing.JTextField txtPesoLiquido;
    private javax.swing.JTextField txtPesoM;
    private javax.swing.JTextField txtUltimaCompra;
    private javax.swing.JTextField txtUltimaVenda;
    private javax.swing.JTextField txtUnidade;
    // End of variables declaration//GEN-END:variables

}
